version: "3.7"

services:
  mautrix-signal:
    container_name: mautrix-signal
    image: dock.mau.dev/mautrix/signal
    restart: unless-stopped
    volumes:
    - bridge_data:/data
    networks:
    - default
    - synapsenet

  db:
    image: postgres:${postgres_version:-13-alpine}
    restart: unless-stopped
    environment:
      POSTGRES_USER: mautrixsignal
      POSTGRES_DATABASE: mautrixsignal
      POSTGRES_PASSWORD: mautrixsignal
    volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
  bridge_data:
  postgres_data:

networks:
  synapsenet:
    external: true
    name: synapsenet

