version: '3.7'

services:
  app:
    image: matrixdotorg/synapse:v1.160.0@sha256:78de1d10bef02e375f861d1cc99f8bedd9381d4f9083ea8b2c22a053477b205f
    restart: unless-stopped
    volumes:
      - synapse_data:/data
      - custom_modules:/usr/local/lib/python3.11/site-packages/custom_modules
    environment:
      - VIRTUAL_HOST=matrix.jfreudenberger.de # the domain where the service should be reached
      - VIRTUAL_PORT=8008 # the port the service listens in the container
      - LETSENCRYPT_HOST=matrix.jfreudenberger.de # the same domain as VIRTUAL_HOST; this enables ssl
    networks:
      - server
      - webproxy
      - synapsenet

  postgresql:
    image: postgres:17@sha256:67f41722b7a8cbdb868a44a4995c846eddfdc2973bccb291ce937dce88ad5675
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=synapse
      - POSTGRES_USER=synapse
      - POSTGRES_DB=synapse
      - POSTGRES_INITDB_ARGS=--encoding='UTF8' --lc-collate='C' --lc-ctype='C'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - server

volumes:
  synapse_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},nfsvers=4.1,soft,noatime
      device: ${NFS_PATH_DATA}
  custom_modules:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},nfsvers=4.1,soft,noatime
      device: ${NFS_PATH_MODULES}
  postgres_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},nfsvers=4.1,hard,noatime
      device: ${NFS_PATH_DATABASE}

networks:
  server:
    external: false
  webproxy:
    external: true
  synapsenet:
    name: synapsenet
