version: '3.3'

services:
  app:
    image: matrixdotorg/synapse:${synapse_version:-latest}
    restart: unless-stopped
    volumes:
      - /media/matrix/matrix_data:/data
    environment:
      - VIRTUAL_HOST=matrix.jfreudenberger.de # the domain where the service should be reached
      - VIRTUAL_PORT=8008 # the port the service listens in the container
      - LETSENCRYPT_HOST=matrix.jfreudenberger.de # the same domain as VIRTUAL_HOST; this enables ssl
    networks:
      - server
      - webproxy
      - synapsenet

  postgresql:
    image: postgres:${postgres_version:-13}
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=synapse
      - POSTGRES_USER=synapse
      - POSTGRES_DB=synapse
      - POSTGRES_INITDB_ARGS=--encoding='UTF8' --lc-collate='C' --lc-ctype='C'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - server

volumes:
  postgres_data:

networks:
  server:
    external: false
  webproxy:
    external: true
  synapsenet:
    name: synapsenet
