version: '3'

services:
  bitwarden:
    image: vaultwarden/server:${vaultwarden_version:-latest}
    restart: unless-stopped
    volumes:
      - bitwarden-data:/data
    environment:
      # - ADMIN_TOKEN=token # set this to enable the admin ui
      - VIRTUAL_HOST=bitwarden.jfreudenberger.de
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=bitwarden.jfreudenberger.de
    networks:
      - webproxy

volumes:
  bitwarden-data:

networks:
  webproxy:
    external: true
    name: webproxy
