version: '3'

services:
  bitwarden:
    image: vaultwarden/server:1.36.0@sha256:d626d04934cd1192ad8ced1adb975099fca78cec33ab467d2d3c923cde7f3b0c
    restart: unless-stopped
    volumes:
      - bitwarden-data:/data
    # environment:
      # - ADMIN_TOKEN=token # set this to enable the admin ui
    networks:
      - webproxy
      - smtp_relay

volumes:
  bitwarden-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},nfsvers=4.1,soft,noatime,sync
      device: ${NFS_PATH_DATA}

networks:
  webproxy:
    external: true
    name: webproxy
  smtp_relay:
    external: true
    name: smtp_relay
