version: '3'

services:
  bitwarden:
    image: vaultwarden/server:1.37.1@sha256:ebdfe70701c60ac0c28c697e787cea767d7972940b786037b29fe0d507f821e8
    restart: unless-stopped
    volumes:
      - bitwarden-data:/data
    # environment:
      # - ADMIN_TOKEN=token # set this to enable the admin ui
    networks:
      - webproxy
      - smtp_relay

volumes:
  bitwarden-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},nfsvers=4.1,soft,noatime,sync
      device: ${NFS_PATH_DATA}

networks:
  webproxy:
    external: true
    name: webproxy
  smtp_relay:
    external: true
    name: smtp_relay
