version: '3'

services:
  bitwarden:
    image: vaultwarden/server:1.37.3@sha256:1587c45feaa479f1f5e8af3b00eded36bff77bcf1880cf8dbf0541706dd470e0
    restart: unless-stopped
    volumes:
      - bitwarden-data:/data
    # environment:
      # - ADMIN_TOKEN=token # set this to enable the admin ui
    networks:
      - webproxy
      - smtp_relay

volumes:
  bitwarden-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},nfsvers=4.1,soft,noatime,sync
      device: ${NFS_PATH_DATA}

networks:
  webproxy:
    external: true
    name: webproxy
  smtp_relay:
    external: true
    name: smtp_relay
