version: '3'

services:
  zot:
    image: ghcr.io/project-zot/zot:${zot_version:-latest}
    restart: unless-stopped
    command: serve /etc/zot/config.yaml
    environment:
      - VIRTUAL_HOST=zot.jfreudenberger.de
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=zot.jfreudenberger.de
    volumes:
      - registry-data:/var/lib/registry
      - registry-config:/etc/zot
    networks:
      - webproxy

volumes:
  registry-data:
  registry-config:

networks:
  webproxy:
    external: true
    name: webproxy
