version: '3'

services:
  anki:
    image: ankicommunity/anki-sync-server-rs:${sync_server_version:-latest}
    restart: unless-stopped
    volumes:
      - anki-data:/app
    environment:
      - VIRTUAL_HOST=anki.jfreudenberger.de
      - VIRTUAL_PORT=27701
      - LETSENCRYPT_HOST=anki.jfreudenberger.de
    networks:
      - webproxy

volumes:
  anki-data:

networks:
  webproxy:
    external: true
    name: webproxy
