version: '3'

services:
  anki:
    image: harbor.jfreudenberger.de:8443/anki/sync:${sync_server_version:-latest}
    restart: unless-stopped
    volumes:
      - anki-data:/root/.syncserver
    environment:
      - VIRTUAL_HOST=anki.jfreudenberger.de
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=anki.jfreudenberger.de
    networks:
      - webproxy

volumes:
  anki-data:

networks:
  webproxy:
    external: true
    name: webproxy
