version: '3'
services:
  postfix:
    image: boky/postfix
    environment:
      - RELAYHOST=${RELAYHOST}
      - RELAYHOST_USERNAME=${RELAYHOST_USERNAME}
      - RELAYHOST_PASSWORD=${RELAYHOST_PASSWORD}
      - ALLOWED_SENDER_DOMAINS=${ALLOWED_SENDER_DOMAINS}
      - MASQUERADED_DOMAINS=${MASQUERADED_DOMAINS}
    networks:
      - smtp_relay

networks:
  smtp_relay:
    name: smtp_relay
