version: '3'
services:
  postfix:
    image: boky/postfix
    restart: unless-stopped
    environment:
      - RELAYHOST=${RELAYHOST}
      - RELAYHOST_USERNAME=${RELAYHOST_USERNAME}
      - RELAYHOST_PASSWORD=${RELAYHOST_PASSWORD}
      - POSTFIX_smtp_tls_security_level=${POSTFIX_smtp_tls_security_level}
      - ALLOWED_SENDER_DOMAINS=${ALLOWED_SENDER_DOMAINS}
      - MASQUERADED_DOMAINS=${MASQUERADED_DOMAINS}
    networks:
      - smtp_relay

networks:
  smtp_relay:
    name: smtp_relay
