version: '3'

services:
  homeassistant:
    restart: unless-stopped
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:${hass_version:-stable}"
    volumes:
      - hass_config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    privileged: true
    network_mode: host

  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:${matter_version:-stable}
    restart: unless-stopped
    volumes:
      - matter_data:/data:rw
      - /run/dbus:/run/dbus:ro
    network_mode: host

  emhass:
    container_name: emhass
    image: ghcr.io/davidusb-geek/emhass:v0.18.2@sha256:2ea230888a66b90a147de99277aff5fedec7f4c45746e1da6533b52ea9388c68
    restart: unless-stopped
    volumes:
      - emhass_data:/share
    environment:
      - SECRETS_PATH=/share/secrets_emhass.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 5000:5000

volumes:
  hass_config:
  matter_data:
  emhass_data:
