version: '3'

services:
  homeassistant:
    restart: unless-stopped
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:${hass_version:-stable}"
    volumes:
      - hass_config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    privileged: true
    network_mode: host

  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:${matter_version:-stable}
    restart: unless-stopped
    volumes:
      - matter_data:/data:rw
      - /run/dbus:/run/dbus:ro
    network_mode: host

  phrase:
    container_name: speech-to-phrase
    image: rhasspy/wyoming-speech-to-phrase:1.4.3@sha256:e532f0dbc6b21285c4c784212003865b9167041927328a767cb0beb1a0beaa20
    command: --hass-websocket-uri 'ws://host.docker.internal:8123/api/websocket' --hass-token '${HASS_TOKEN}' --retrain-on-start
    volumes:
      - phrase_models:/models
      - phrase_train:/train
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 127.0.0.1:10300:10300

  piper:
    container_name: piper
    image: rhasspy/wyoming-piper:2.4.2@sha256:72ee1b06b062cb14f4a70de002eb420a068efd5a7a8cb7620be6bf600307f867
    command: --voice de_DE-eva_k-x_low
    volumes:
      - piper_data:/data
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    ports:
      - 127.0.0.1:10200:10200

  emhass:
    container_name: emhass
    image: ghcr.io/davidusb-geek/emhass:v0.18.1@sha256:c4b436a58ee0a01aa53ebbfa6b324cddbbd108ea70a7c29c74aebdafddbc6d6c
    volumes:
      - emhass_data:/share
    environment:
      - SECRETS_PATH=/share/secrets_emhass.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 5000:5000

volumes:
  hass_config:
  matter_data:
  phrase_models:
  phrase_train:
  piper_data:
  emhass_data:
