version: "3"

services:
  gitea:
    image: codeberg.org/forgejo/forgejo:11.0.14@sha256:afb609f099fdfc85aed99fa763604102cfc6525b78b3637382b2ac48d9d80f7c
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=mysql
      - FORGEJO__database__HOST=db:3306
      - FORGEJO__database__NAME=gitea
      - FORGEJO__database__USER=gitea
      - FORGEJO__database__PASSWD=gitea
      - FORGEJO__server__DOMAIN=git.jfreudenberger.de
      - FORGEJO__server__SSH_DOMAIN=git.jfreudenberger.de
      - FORGEJO__server__ROOT_URL=https://git.jfreudenberger.de
      - FORGEJO__server__LFS_JWT_SECRET=${LFS_JWT_SECRET}
      - FORGEJO__security__SECRET_KEY=${SECRET_KEY}
      - FORGEJO__security__INTERNAL_TOKEN=${INTERNAL_TOKEN}
      - FORGEJO__security__INSTALL_LOCK=${INSTALL_LOCK:-true}
      - FORGEJO__service__DISABLE_REGISTRATION=${DISABLE_REGISTRATION:-true}
      - FORGEJO__service__NO_REPLY_ADDRESS=${NO_REPLY_ADDRESS:-noreply@jfreudenberger.de}
      - FORGEJO__oauth2__JWT_SECRET=${OAUTH_JWT_SECRET}
      - FORGEJO__mailer__ENABLED=${MAILER_ENABLED:-false}
      - FORGEJO__mailer__SMTP_ADDR=${SMTP_ADDR}
      - FORGEJO__mailer__SMTP_PORT=${SMTP_PORT}
      - FORGEJO__mailer__FROM=${MAILER_FROM}
      - FORGEJO__mailer__USER=${MAILER_USER}
      - FORGEJO__mailer__PASSWD=${MAILER_PASSWD}
      - FORGEJO__actions__ENABLED=${ACTIONS_ENABLED}
      - FORGEJO__other__SHOW_FOOTER_VERSION=${SHOW_FOOTER_VERSION:-false}
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    networks:
      - forgejo
      - webproxy
      - smtp_relay

  db:
    image: mariadb:10.7@sha256:9a48ac9f196f3d4fd6fea2cab59a49df9e7ca459bf14b2f7b85a0e38a5454571
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=gitea
      - MARIADB_USER=gitea
      - MARIADB_PASSWORD=gitea
      - MARIADB_DATABASE=gitea
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - forgejo

volumes:
  gitea-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},nfsvers=4.1,soft,noatime,sync
      device: ${NFS_PATH_DATA}
  mariadb-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},nfsvers=4.1,hard,noatime
      device: ${NFS_PATH_DATABASE}

networks:
  forgejo:
  webproxy:
    external: true
    name: webproxy
  smtp_relay:
    external: true
    name: smtp_relay
