services:
  hawser:
    image: ghcr.io/finsys/hawser:v0.2.42@sha256:79f926e8d8fe31c0dfe90858f90b69bfd4cfbb113472605620b91a4b444dd557
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HAWSER_STACKS:-/opt/hawser-stacks}:${HAWSER_STACKS:-/opt/hawser-stacks}
    env_file: .env
