version: '3'
services:
  mensa-parser:
    image: harbor.jfreudenberger.de:8443/mensa-parser/app:latest
    container_name: mensa-parser
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=mensa.jfreudenberger.de
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=mensa.jfreudenberger.de
    networks:
      - webproxy

networks:
  webproxy:
    external: true
    name: webproxy
