version: '3.5'
services:
  portainer:
    image: portainer/portainer-ce:2.11.0
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 8000:8000 # This is used for portainer edge agents to connect
    environment:
      - VIRTUAL_HOST=portainer.jfreudenberger.de
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=portainer.jfreudenberger.de
    networks:
      - webproxy

volumes:
  portainer_data:

networks:
  webproxy:
    external: true
    name: webproxy
