version: "3"
services:
  website:
    image: zot.jfreudenberger.de/website/app:${website_version:-latest}
    environment: 
      - VIRTUAL_HOST=jfreudenberger.de,www.jfreudenberger.de # the domain where the service should be reached
      - VIRTUAL_PORT=80 # the port the service listens in the container
      - LETSENCRYPT_HOST=jfreudenberger.de,www.jfreudenberger.de # the same domain as VIRTUAL_HOST; this enables ssl
    networks:
      - webproxy
    restart: always
      
networks:
 webproxy:
   name: webproxy
   external: true

