version: "3.7"

services:
  mautrix-whatsapp:
    container_name: mautrix-whatsapp
    image: dock.mau.dev/mautrix/whatsapp
    restart: unless-stopped
    volumes:
    - bridge_data:/data
    networks:
    - synapsenet

volumes:
  bridge_data:

networks:
  synapsenet:
    external: true
    name: synapsenet

